services:
  gitea-service:
    image: gitea/gitea:1.22.4
    container_name: gitea
    environment:
     - USER_UID=1000
     - USER_GID=1000
     # https://docs.gitea.com/next/administration/config-cheat-sheet#webhook-webhook
     - GITEA__webhook__ALLOWED_HOST_LIST=jenkins # loopback also valid
     - GITEA__webhook__SKIP_TLS_VERIFY=true
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
     - "5555:3000"
     - "222:22"
  jenkins:
    container_name: jenkins
    image: "jenkins/jenkins:lts-jdk17"
    volumes:
      - jenkins_home:/var/jenkins_home

    ports: 
      - "8080:8080"
      - "50000:50000"
    networks:
      - gitea
networks:
  gitea:
    external: false

volumes:
  jenkins_home:


